server:
  port: 8111

spring:
  application:
    name: gateway-service



  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

  config:
    import: "optional:configserver:"

  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-service


    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: account-service
          uri: lb://account-service
          predicates:
            - Path=/bankingapp/accounts/**
          filters:
            - name: JwtFilter
            - StripPrefix=1

        - id: transaction-service
          uri: lb://transaction-service
          predicates:
            - Path=/bankingapp/transactions/**
          filters:
            - name: JwtFilter
            - StripPrefix=1

        - id: fund-transfer-service
          uri: lb://fund-transfer-service
          predicates:
            - Path=/bankingapp/fundTransfers/**
          filters:
            - name: JwtFilter
            - StripPrefix=1

        - id: notification-service
          uri: lb://notification-service
          predicates:
            - Path=/notifications/**

        - id: auth-service
          uri: lb://authentication-service
          predicates:
            - Path=/bankingapp/auth/**

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT:http://registry-service:8761/eureka/}

jwt:
  secret: ayushkumardassoftwaredeveloper98908283119

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.mybank.bankingapp: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: "*"  # Expose all Actuator endpoints
  endpoint:
    health:
      show-details: always